config/routes.rb
Finance::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users

  resources :users do
    resources :categories
    resources :transactions, :except => [ :new, :create ]
    resources :incomes, :only => [:index, :new, :create ]
    resources :expenses, :only => [:index, :new, :create ]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user

  def to_s
    name
  end

end

app/models/expense.rb
class Expense < Transaction

  private
  def change_user
    self.user.amount -= amount
  end

  def update_user
    self.user.amount += amount_was
  end
end

app/models/income.rb
class Income < Transaction

  private
  def change_user
    self.user.amount += amount
  end

  def update_user
    self.user.amount -= amount_was
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  attr_accessible :amount, :concept, :date, :user_id, :category_id

  before_update :update_user
  after_save :change_user
  after_save :save_user
  after_initialize :default_date

  validates :amount, :numericality => { :greater_than => 0 }
  validates :category, :presence => true

  default_scope order("date desc, created_at desc")

  private

  def default_date
    self.date = Date.today
  end

  def save_user
    user.save
  end

  def change_user
  end

  def update_user
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :amount

  has_many :transactions
  has_many :categories

  before_save :default_values
  def default_values
    self.amount ||= 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  belongs_to :user
  before_filter :authenticate_user!
end

app/controllers/expences_controller.rb
class ExpensesController <  TransactionsController

  def index
    @account = Account.find params[:account_id]
    @transactions = Income.where(account_id: @account.id)
  end

  def new
    @account = Account.find params[:account_id]
    @transaction = Expense.new
  end
end

app/controllers/expenses_controller.rb
class ExpensesController <  TransactionsController

  def index
    @user = User.find params[:user_id]
    @transactions = Expense.where(user_id: @user.id)
  end

  def new
    @user = User.find params[:user_id]
    @transaction = Expense.new
  end

  def create
    @user = User.find params[:user_id]
    @transaction = Expense.new(params[:expense])
    @transaction.user = @user

    if @transaction.save
      redirect_to user_transactions_path(@user)
    else
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @transactions = current_user.transactions.limit(5)
  end
end

app/controllers/incomes_controller.rb
class IncomesController <  TransactionsController

  def index
    @user = User.find params[:user_id]
    @transactions = Income.where(user_id: @user.id)
  end

  def new
    @user = User.find params[:user_id]
    @transaction = Income.new
  end

  def create
    @user = User.find params[:user_id]
    @transaction = Income.new(params[:income])
    @transaction.user = @user

    if @transaction.save
      redirect_to user_transactions_path(@user)
    else
      render :new
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController <  InheritedResources::Base
  actions :all, :except => [ :new, :create ]

  belongs_to :user
  before_filter :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def income_button user
    link_to new_user_income_path(user), class: 'btn btn-success' do
      content_tag(:i, "", class: 'icon-plus-sign icon-white')
    end
  end

  def expense_button user
    link_to new_user_expense_path(user), class: 'btn btn-danger' do
      content_tag(:i, "", class: 'icon-minus-sign icon-white')
    end
  end

  def new_button url, name = "New"
    link_to name, url, class: 'btn btn-mini btn-primary span1'
  end

  def edit_button url, name = "Edit"
    link_to name, url, class: 'btn btn-mini'
  end

  def destroy_button url, name = "Destroy"
    link_to name, url, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-mini'
  end

  def show_button url, name = "Show"
    edit_button(url, name)
  end
end

app/views/categories/_form.html.haml
= simple_form_for([user, category]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form', :user => @user, :category => @category

= link_to 'Show', user_caterfory_path(@category)
\|
= link_to 'Back', user_categories_path(@user)

app/views/categories/index.html.haml
%h1 Listing categories

%table.table.table-striped
  %tr
    %th Name
    %th Actions

  - @categories.each do |category|
    %tr
      %td= category.name
      %td
        = show_button(user_category_path(category.user, category)) + edit_button(edit_user_category_path(category.user, category)) + destroy_button(user_category_path(category.user, category))

%br

= new_button new_user_category_path(@user)

app/views/categories/new.html.haml
%h1 New category

= render 'form', :user => @user, :category => @category

= link_to 'Back', user_categories_path(@user)

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_user_category_path(@user, @category)
\|
= link_to 'Back', user_categories_path(@user)

app/views/home/index.html.haml
%table.table-condensed
  %td= gravatar_image_tag(current_user.email)
  %td
    %b= current_user.name
    %br
    %b="$ #{current_user.amount}"
    %br
    = income_button current_user
    = expense_button current_user

=render partial: "transactions/transactions", locals: { transactions: @transactions, user: current_user }

= link_to "categories", user_categories_path(current_user), class: 'btn btn-mini btn-primary span1'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Finance", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Finance"
      %meta{:content => content_for?(:description) ? yield(:description) : "Finance", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/transactions/_form.html.haml
= simple_form_for([user, transaction], :html => { :class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs.row
    = f.input :date, as: :string, input_html: { class: 'date_picker input-small' }, :wrapper_html => { :class => 'span3' }
    = f.input :amount, input_html: { class: 'input-mini' }, :wrapper_html => { :class => 'span1' }
  = f.association :category, input_html: { class: 'input-xlarge'}
  = f.input :concept, input_html: { rows: "3", class: 'input-xlarge' }

  .form-actions
    = f.button :submit

app/views/transactions/_transactions.html.haml
%table.table.table-striped
  %tr
    %th Date
    %th Category
    %th Amount
    %th Concept
    %th Actions

  - transactions.each do |transaction|
    %tr
      %td= transaction.date
      %td= link_to transaction.category, user_category_path(user, transaction.category)
      %td= transaction.amount
      %td= transaction.concept
      %td
        = show_button(user_transaction_path(user, transaction)) + edit_button(edit_user_transaction_path(user, transaction)) + destroy_button(user_transaction_path(user, transaction))

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form', :transaction => @transaction, :user => @user

= link_to 'Show', user_transaction_path(@transaction)
\|
= link_to 'Back', user_transactions_path(@user)

app/views/transactions/index.html.haml
%h1 Listing transactions

=render partial: "transactions", locals: {transactions: @transactions, user: @user}
%br

= income_button @user
= expense_button @user

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form', :transaction => @transaction, :user => @user

= link_to 'Back', user_transactions_path(@user)

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @transaction.date
%p
  %b Category:
  = @transaction.category
%p
  %b Amount:
  = @transaction.amount
%p
  %b Concept:
  = @transaction.concept


= link_to 'Edit', edit_user_transaction_path(@user, @transaction)
\|
= link_to 'Back', user_transactions_path(@user)

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}